# PostgreSQL database configuration

connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: drew.nocton
  password: postgres
  timeout: 5000

development:
  <<: *connection
  database: postgres

test:
  <<: *connection
  database: rails_test
